import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

// Import Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata export (This should be correct for Next.js 13.x)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Default export for RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Additional meta tags or other head content */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <Provider>{children}</Provider>
       
      </body>
    </html>
  );
}
